name: "Build and Deploy"

on:
  workflow_call:
    inputs:
      installation-method:
        required: true
        type: string
        description: "installation method, can be any of create, reinstall, upgrade"
    secrets:
      GH_PKG_LOGIN:
        required: true
      GH_PKG_TOKEN:
        required: true

jobs:
  clone-evm:
    name: "Clone Repo"
    runs-on: ubuntu-latest
    steps:
      - name: Run Local Evm Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PKG_TOKEN }}
          repository: bitfinity-network/evm-canister
          ref: develop
          path: ./evm

  build-local-evm:
    name: "Build"
    uses: bitfinity-network/ci-wf/.github/workflows/build-n-test.yml@main
    with:
      runs-on: 4x150g-runner
      container-image: ghcr.io/bitfinity-network/ic-dev-full:rust1.70-dfx0.14-rc-2022-09-30
      git-fetch-depth: "0"
      audit-allow-warnings: true
      cargo-clippy-extra-args: "-- -D warnings"
      output-artifact: artifact-evm
      init-script: |
        cd ./evm
        ./scripts/build_solidity_smart_contracts.sh
      artifact-pre-script: |
        ./scripts/build.sh
        ./scripts/dfx/deploy_local.sh ${{ inputs.installation-method }}
      enable-target-cache: true
    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}
      gh_login: ${{ secrets.GH_PKG_LOGIN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - name: Clear yarn cache
        run: cd ~/ && yarn cache clean
      - name: Install plugin Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Test
        run: yarn test
