name: "Build and Deploy"

on:
  workflow_call:
    secrets:
      GH_PKG_LOGIN:
        required: true
      GH_PKG_TOKEN:
        required: true

jobs:
  build-local-evm:
    name: "Build"
    uses: bitfinity-network/ci-wf/.github/workflows/build-n-test.yml@main
    background: true
    with:
      runs-on: 4x150g-runner
      container-image: ghcr.io/bitfinity-network/ic-dev-full:rust1.70-dfx0.14-rc-2022-09-30
      git-fetch-depth: "0"
      audit-allow-warnings: true
      cargo-clippy-extra-args: "-- -D warnings"
      output-artifact: artifact-evm
      enable-target-cache: true
      init-script: |
        git submodule update --init --recursive
        curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
        apt-get update && apt-get install -y nodejs
        cd submodules/evm-canister && ls -la
        ./scripts/build_solidity_smart_contracts.sh
        echo "build_solidity_smart_contracts completed"
        echo "Run build"
        export ETHEREUM_GENESIS_ACCOUNTS=0
        ./scripts/build.sh
        ./scripts/dfx/deploy_local.sh create
    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}
      gh_login: ${{ secrets.GH_PKG_LOGIN }}

  run-client-tests:
    name: "Run Evm Client tests"
    needs: build-local-evm
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Backend to Start
        run: sleep 20
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - name: Clear yarn cache
        run: yarn cache clean
      - name: Install plugin Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Test
        run: yarn test
