name: CI / CD workflow for Prod
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
env:
  LOCAL_TEST_SEED_PHRASE: ""
  IC_HOST: http://127.0.0.1:8080
  RPC_URL: http://127.0.0.1:8545

jobs:
  build-local-evm:
    uses: ./.github/workflows/build-deploy-local.yml
    with:
      installation-method: create
    secrets:
      GH_PKG_LOGIN: ${{ secrets.GH_PKG_LOGIN }}
      GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
