name: CI / CD workflow for Prod
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
env:
  LOCAL_TEST_SEED_PHRASE: ""
  IC_HOST: http://127.0.0.1:8080
  RPC_URL: http://127.0.0.1:8545

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Run Local Evm Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PKG_TOKEN }}
          repository: bitfinity-network/evm-canister
          ref: develop
          path: ./evm

      - name: Build and run local
        uses: bitfinity-network/ci-wf/.github/workflows/build-n-test.yml@main
        with:
          runs-on: 4x150g-runner
          container-image: ghcr.io/bitfinity-network/ic-dev-full:rust1.70-dfx0.14-rc-2022-09-30
          git-fetch-depth: "0"
          audit-allow-warnings: true
          cargo-clippy-extra-args: "-- -D warnings"
          output-artifact: artifact-evm
          init-script: |
            cd ./evm
            ./scripts/build_solidity_smart_contracts.sh
          artifact-pre-script: |
            ./scripts/build.sh

      - name: Run Local build
        run: |
          cd evm
          echo "Build Smart Contract"
          ./scripts/dfx/deploy_local.sh create

      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - name: Clear yarn cache
        run: yarn cache clean
      - name: Install plugin Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Test
        run: yarn test
